version: "3.9"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    # environment:
      # Optional: uncomment and set to enable email notifications
      # USER_EMAIL: "your-email@gmail.com"
      # USER_PASS: "your-app-password"

  frontend:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro

  mongo:
    image: mongo:8
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
